name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build and load docker image
        run: |
          export target="github:astridyu/khinsider-scraper/$GITHUB_SHA#khinsider-scraper-docker"
          docker load < GC_DONT_GC=1 nix build --show-trace $target

      - name: Tag and upload Docker images
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker tag ghcr.io/astridyu/khinsider-scraper ghcr.io/astridyu/khinsider-scraper:latest
          docker push -a